In [5]:
pip install scikit_learn

Requirement already satisfied: scikit_learn in c:\users\brahi\desktop\predict_employee_resign_appv2\venv\lib\site-packages (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\brahi\desktop\predict_employee_resign_appv2\venv\lib\site-packages (from scikit_learn) (2.4.6)
Requirement already satisfied: scipy>=1.6.0 in c:\users\brahi\desktop\predict_employee_resign_appv2\venv\lib\site-packages (from scikit_learn) (1.17.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\brahi\desktop\predict_employee_resign_appv2\venv\lib\site-packages (from scikit_learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\brahi\desktop\predict_employee_resign_appv2\venv\lib\site-packages (from scikit_learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.1
[notice] To update, run: C:\Users\brahi\Desktop\Predict_Employee_Resign_appv2\venv\Scripts\python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
import numpy as np
from imblearn.pipeline import Pipeline
from imblearn.combine import SMOTEENN
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import joblib

In [7]:
#!python --version
import sys,os
print(sys.version)

3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

In [8]:
print(os.getcwd())

C:\Users\brahi\Desktop\Predict_Employees_Resign

In [9]:
# Read the file
df=pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

In [10]:
# display the 5 first rows
df.head(3)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 510.8 KB

In [12]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [13]:
df.shape

(1470, 35)

In [14]:
df.Attrition.value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [15]:
# display the percentage of yes and no in the dataset
df.Attrition.value_counts(normalize=True)*100

Attrition
No     83.877551
Yes    16.122449
Name: proportion, dtype: float64

#### ~84% employees stay
#### ~16% employees leave
#### So the model may become biased toward predicting "No" most of the time.

In [16]:
x = df.drop('Attrition', axis=1)
y = df['Attrition'].map({'Yes': 1, 'No': 0})

# convert pandas string dtype to object for compatibility reasons with older libraries or pipelines.
x = x.astype({col: 'object' for col in x.select_dtypes(include=['string']).columns})

# feature lists
numerical_features = x.select_dtypes(include=['int64', 'float64']).columns.tolist()

categorical_features = x.select_dtypes(include=['object']).columns.tolist()

In [17]:
categorical_features

['BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

#### Display values of each categorical variable

In [18]:
df.BusinessTravel.value_counts()

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

In [19]:
BusinessTravel_values=['Travel_Rarely','Travel_Frequently','Non-Travel']

In [20]:
df.Department.value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [21]:
Department_values=['Research & Development','Sales','Human Resources']

In [22]:
df.EducationField.value_counts()

EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

In [23]:
EducationField_values=['Life Sciences','Medical','Marketing','Technical Degree','Other','Human Resources']

In [24]:
df.Gender.value_counts()

Gender
Male      882
Female    588
Name: count, dtype: int64

In [25]:
Gender_values=['Male','Female']

In [26]:
df.JobRole.value_counts()

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

In [27]:
JobRole_values=['Sales Executive','Research Scientist','Laboratory Technician','Manufacturing Director','Healthcare Representative','Managers','Sales Representative','Research Director','Human Resources']

In [28]:
df.MaritalStatus.value_counts()

MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

In [29]:
MaritalStatus_values=['Married','Single','Divorced']

In [30]:
df.Over18.value_counts()

Over18
Y    1470
Name: count, dtype: int64

In [31]:
Over18_values=['Y']

In [32]:
df.OverTime.value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [33]:
OverTime_values=['No','Yes']

In [34]:
# check for null values
df[categorical_features].isnull().sum()

BusinessTravel    0
Department        0
EducationField    0
Gender            0
JobRole           0
MaritalStatus     0
Over18            0
OverTime          0
dtype: int64

In [35]:
df[numerical_features].isnull().sum()

Age                         0
DailyRate                   0
DistanceFromHome            0
Education                   0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobSatisfaction             0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

#### There are no missing (null) values in the dataset

In [36]:
df_copy=df.copy()  # keep a copy of the file

In [38]:
# check if the mapping is correct
x.head(3)

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,...,1,80,0,8,0,1,6,4,0,5
1,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,...,4,80,1,10,3,3,10,7,1,7
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,...,2,80,0,7,3,3,0,0,0,0

In [39]:
x.columns

Index(['Age', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [40]:
y

0       1
1       0
2       1
3       0
4       0
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: Attrition, Length: 1470, dtype: int64

In [41]:
#DTC=DecisionTreeClassifier(criterion='gini',max_depth=6,min_samples_leaf=8,random_state=42)

In [43]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            categorical_features
        )
    ],
    remainder='passthrough'
)

In [44]:
pipeline = Pipeline(
    steps=[
        ('preprocess', preprocessor),
        ('smoteenn', SMOTEENN(random_state=42)),
        ('model', DecisionTreeClassifier(
            criterion='gini',
            max_depth=6,
            min_samples_leaf=8,
            random_state=42
        ))
    ]
)

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [46]:
pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['BusinessTravel',
                                                   'Department',
                                                   'EducationField', 'Gender',
                                                   'JobRole', 'MaritalStatus',
                                                   'Over18', 'OverTime'])])),
                ('smoteenn', SMOTEENN(random_state=42)),
                ('model',
                 DecisionTreeClassifier(max_depth=6, min_samples_leaf=8,
                                        random_state=42))])

In [47]:
from sklearn.metrics import classification_report

y_pred = pipeline.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.83      0.86       255
           1       0.27      0.41      0.32        39

    accuracy                           0.77       294
   macro avg       0.58      0.62      0.59       294
weighted avg       0.82      0.77      0.79       294

In [41]:
y_pred[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

#### Class 0 (No Attrition)
#### ✔ Model is very good at predicting employees who stay
#### ✔ Most “No” predictions are correct
#### Class 1 (Attrition - IMPORTANT CLASS)
❗ Recall = 0.41
Model only catches 41% of employees who actually leave
 It misses 59% of real attrition cases
 Precision = 0.27
 When model predicts “Yes”, it's correct only 27% of the time
Many false alarms

In [48]:
# I will tray an other model : Random Forest
from sklearn.ensemble import RandomForestClassifier

model_RF = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    class_weight='balanced',
    random_state=42
)

In [49]:
pipeline_rf=Pipeline(
    steps = [
            ('preprocess',preprocessor),
            ('smoteenn', SMOTEENN(random_state=42)),
            ('model_rf', RandomForestClassifier(
                         n_estimators=200,
                         max_depth=8,
                         class_weight='balanced',
                         random_state=42)
            )
])

In [50]:
pipeline_rf.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['BusinessTravel',
                                                   'Department',
                                                   'EducationField', 'Gender',
                                                   'JobRole', 'MaritalStatus',
                                                   'Over18', 'OverTime'])])),
                ('smoteenn', SMOTEENN(random_state=42)),
                ('model_rf',
                 RandomForestClassifier(class_weight='balanced', max_depth=8,
                                        n_estimators=200, random_state=42))])

In [51]:
y_pred_rf = pipeline_rf.predict(x_test)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.90      0.93      0.92       255
           1       0.42      0.33      0.37        39

    accuracy                           0.85       294
   macro avg       0.66      0.63      0.64       294
weighted avg       0.84      0.85      0.84       294

### Conclusion :
#####  “The Random Forest model improved precision for attrition prediction from 27% to 42%, reducing false positives. However, recall decreased from
#####  42% to 33%, meaning more attrition cases were missed. This highlights the precision-recall tradeoff commonly encountered in balanced 
#####    classification ### problems.”

In [52]:
# Save the model 
from joblib import dump , load

In [53]:
# save model
dump(pipeline_rf, "attrition_pipeline.joblib")

['attrition_pipeline.joblib']

In [54]:
# load the model
model = load("attrition_pipeline.joblib")

In [55]:
y_pred_rf = model.predict(x_test)

In [57]:
print(y_pred_rf[0:5])

[0 0 1 0 0]